### ISSUE TITLE
panic at range end out of range for slice

### ISSUE THREAD

**Issue by alexanderkjall** [image-rs/image-gif#117] opened 2021-10-12 10:26 UTC
## What I expected to happen

An error about an invalid image being returned.

## What happened

A panic with the following error and stack trace:

```
thread 'main' panicked at 'range end index 525312 out of range for slice of length 286200', /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/gif-0.11.2/src/reader/mod.rs:290:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:41:5
   3: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:251:13
   4: <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:291:9
   5: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:26:9
   6: gif::reader::Decoder<R>::read_into_buffer
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/gif-0.11.2/src/reader/mod.rs:290:28
   7: <image::codecs::gif::GifDecoder<R> as image::image::ImageDecoder>::read_image
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/codecs/gif.rs:111:13
   8: image::image::decoder_to_vec
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/image.rs:491:5
   9: image::dynimage::decoder_to_image
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/dynimage.rs:1117:23
  10: image::dynimage::DynamicImage::from_decoder
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/dynimage.rs:194:9
  11: image::io::free_functions::load
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/io/free_functions.rs:67:36
  12: image::dynimage::load_from_memory_with_format
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/dynimage.rs:1320:5
  13: image::dynimage::load_from_memory
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.14/./src/dynimage.rs:1305:5
  14: image_reproduce::main
             at ./src/main.rs:58:13
  15: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Steps to reproduce

Can be reproduced with this program:

```
fn main() {
    let data = vec![0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x03, 0x00, 0x2a, 0x5d, 0xe8, 0x66,
                    0x61, 0x72, 0x62, 0x66, 0x45, 0x6c, 0x64, 0x2c, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x01, 0x01, 0x02, 0x00, 0x00, 0xd6, 0x4a, 0x60, 0xcf, 0x67, 0x0f,
                    0xc7, 0x6f, 0x6b, 0xf4, 0x19, 0xf7, 0xbf, 0xbd, 0xe2, 0xe1, 0xbf, 0xf5,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x1a, 0xfe, 0x19, 0x9d, 0xa2, 0x7e,
                    0xb8, 0xd1, 0x4a, 0x54, 0xa8, 0x56, 0x3b, 0x6d, 0x0c, 0x66, 0xbd, 0x89,
                    0xf6, 0xcf, 0xbb, 0xff, 0x44, 0x88, 0xae, 0x64, 0x6a, 0x7f, 0x0a, 0x46,
                    0x45, 0xef, 0xcb, 0x15, 0xc8, 0xde, 0x75, 0xce, 0x67, 0x65, 0x66, 0xf4,
                    0xe2, 0x65, 0x17, 0x55, 0xf7, 0x3a, 0x5b, 0x65, 0xfd, 0xef, 0xb9, 0x74,
                    0x2f, 0x7e, 0xaa, 0xc7, 0x4c, 0x92, 0x91, 0xdb, 0xf9, 0x4d, 0x91, 0x82,
                    0x09, 0x95, 0x32, 0x63, 0xb2, 0x3a, 0xe0, 0xd7, 0x4a, 0x7a, 0x47, 0xbd,
                    0x85, 0xb4, 0x41, 0x9d, 0x78, 0x12, 0x51, 0xf9, 0x57, 0xdb, 0xdc, 0x3e,
                    0x92, 0x60, 0x0c, 0x66, 0xef, 0x24, 0xf5, 0xbe, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08,
                    0x08, 0x08, 0x08, 0x47, 0xd3, 0x5e, 0x03, 0xd9, 0xa6, 0x78, 0xb2, 0x0f,
                    0xc1, 0xc3, 0x9c, 0xda, 0x3a, 0x34, 0x42, 0x3e, 0x52, 0xe0, 0xad, 0x91,
                    0x50, 0x36, 0x37, 0x30, 0xad, 0x91, 0x41, 0x64, 0x6f, 0x62, 0x65, 0x00,
                    0x12, 0x14, 0x37, 0x30, 0x38, 0x37, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x2c, 0xa1, 0xa4, 0xd6, 0x4a, 0x60, 0xcf, 0x67, 0x0f, 0xc7, 0x6f, 0x6b,
                    0xf4, 0x19, 0xf7, 0xbf, 0xbd, 0xe2, 0xe1, 0xbf, 0xf5, 0x47, 0xd3, 0x5e,
                    0x03, 0xd9, 0xa6, 0x78, 0xb2, 0x0f, 0xc1, 0xc3, 0x9c, 0xda, 0x3a, 0x34,
                    0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34,
                    0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34,
                    0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34,
                    0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x34, 0x42, 0x3e, 0x52, 0xe0,
                    0xad, 0x91, 0x12, 0x14, 0x58, 0x1c, 0x59, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x06, 0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x2c, 0xa1, 0xa4, 0xd6, 0x4a, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x50, 0x88, 0x80, 0x00, 0x00,
                    0x00, 0xdb, 0xc2, 0xad, 0x12, 0xd7, 0x0a, 0x56, 0x68, 0x11, 0xdb, 0x5f,
                    0x5d, 0x47, 0xf6, 0x90, 0x2e, 0x17, 0x59, 0x06, 0x5d, 0x01, 0x6c, 0x00,
                    0x9e, 0x2a, 0x96, 0x7f, 0xeb, 0xfb, 0x97, 0x82, 0x7a, 0xa4, 0x0a, 0xca,
                    0xe0, 0xd3, 0x46, 0xa2, 0xa9, 0x23, 0x91, 0xcb, 0x72, 0x4e, 0xbc, 0xb7,
                    0x0f, 0x44, 0x73, 0x46];

    let _ = image::load_from_memory(&data);
}
```

**Comment by saethlin** [comment] 2021-11-20 00:21
I think this was fixed in 45025539ffe627fee560b1b0d09c54b320f76f20 and the fix is in the latest release, right? I can't reproduce on the latest release, and that's what I can work out from `git-blame`.

**Closed** 2021-12-23 15:27 UTC
Labels: help wanted
